### ISSUE TITLE
Jobs browse performance issues

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2871]
Loading recent runs and browsing jobs appear to take nearly a second.

**Comment by xiroV** [comment]
Can't reproduce locally. Obviously there will be less delay when running locally, but if this was caused by inefficient code on the backend, I think it would still be noticeable in comparison to other calls.

On current dev: ~700ms for 3 jobs (~8 kb)
Locally: ~30ms for 11 jobs (~25 kb)

Thus I think this issue is either already fixed, or it has to do with something specific to the dev setup/environment.

**Comment by xiroV** [comment]
Disregard my last comment. As Dan made me aware of, the difference in response time is due to the amount of data (i.e. number of jobs) on dev compared to my local environment.

The query for browsing jobs is definitely causing the performance issues. I've played a bit with the query, and especially

```sql
array_agg(
        distinct
        case
            when :username = '_ucloud' then 'ADMIN'
            when pm.role = 'PI' then 'ADMIN'
            when pm.role = 'ADMIN' then 'ADMIN'
            when r.created_by = :username and r.project is null then 'ADMIN'
            when :username = '#P_' || r.provider then 'PROVIDER'
            when r.public_read and acl.permission is null then 'READ'
            else acl.permission
            end
    ) as permissions,
array_remove(array_agg(distinct other_acl), null),array[]::provider.resource_update[]
```
(in select of browseQuery, job-orchestrator) seems to take a lot of time.
