### ISSUE TITLE
Allow invite to project via link

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#3421]
PIs and admins of a project should be able to create an invitation link to a project. This link should be accessible by any UCloud user, once used, the authenticated user must automatically be added to the project.

This feature depends on being able to pass a "redirection" page, see #3420.

**Comment by xiroV** [comment]
# Project invite link design proposal

This is a design document of a feature for UCloud which allows admins of a project to invite members from a generated link. The hard requirements for the feature are as follows:

 - An invite link must only live X number of days,
 - it should be possible to deactivate/delete a link,
 - an invitee should be able to join the project even if not a user on UCloud yet.

The proposal also include solutions to some features, which are not hard requirements, but offer a lot of flexibility for the PI and admins of a project. These include the ability to:

 - Create multiple invite links for a project,
 - assign invitees to a specific role and/or project groups for each link.

These features combined will allow the PI and admins to create more complex project membership structures already before members have joined the project. Another bonus is that this can increase the level of security, if used correctly. An example would be to automatically assign invitees to an unprivileged project group, and let the admins manually assign them to different project groups at a later point.

## Front-end
The admin of a project is able to generate links for invitees. This is done from the Project Members page.

The existing *Bulk invite* feature will be removed, but otherwise the *Project members* UI is preserved. The *Bulk invite* modal will be exchanged with the new *Invite with link* interface.

![Invitation links-interface proposal with no links, with 2 links and the link-settings page respectively.](https://user-images.githubusercontent.com/911284/214563065-49f1f22f-0dd6-4ba6-b166-15a9b4a56954.png)


## Database structure

Two new database tables will be added with the following structure.

The `invite_links` table store the tokens of the invite links, the associated project id, the expiration time, and the role users clicking on the link should be assigned to.

```sql
create table if not exists project.invite_links (
    token uuid primary key not null,
    project_id text not null references project.projects(id),
    expires timestamptz not null,
    role_assignment text not null default 'USER'
);
```

The `invite_link_group_assignments` table store which groups invitees should be assigned to when clicking an invite link.

```sql
create table if not exists project.invite_link_group_assignments (
    link_token uuid not null references project.invite_links(token),
    group_id varchar(255) not null references project.groups(id),
    primary key (link_token, group_id)
);
```

## Link Management API

For link generation and management (done by the PI or admin of the project) the `ProjectsV2` API will be extended with the following new end-points.

### `createInviteLink`

End-point used for creating a link for a project. The project id is needed which can be taken from the header. This will generate a unique token which will be exposed to the invitees.

The token should consist of randomly generated numbers and characters such as a UUID. The most important thing is that it is not possible to *guess* this token.

```kotlin
typealias CreateInviteLinkRequest = Unit
```

```kotlin
typealias CreateInviteLinkResponse = Unit
```

The following will be inserted into the `project.invite_links` table:

 - `token`: The generated token,
 - `project_id`: The project ID taken from the header,
 - `expires`: a timestamp X number of days into the future,
 - `role_assignment`: `USER` (no need to set; default value in `project.invite_links`),

Should respond `200 OK` on success, or fail with an appropriate error in any of the following cases:

 - The user making the request is not an admin or PI of the current project.


### `browseInviteLinks`

End-point used for fetching the invite links for a project. The project ID is taken from the header.

```kotlin
typealias BrowseInviteLinksRequest = Unit
```

The backend will respond with a page of invite links, defined as:

```kotlin
data class InvitationLink(
    val token: String,
    val expires: Long,
    val groupAssignments: List<ProjectGroup>,
    val roleAssignment: ProjectRole = ProjectRole.USER
)
```

```kotlin
typealias BrowseInviteLinksResponse = PageV2<InvitationLink>
```

The page of invitation links will only include links which are not expired.

An example of a response:

```json
{
  "itemsPerPage": 100,
  "items": [
    {
      "token": "ABCD1234",
      "expires": 1674052194,
      "group_assignments": [
        {
          "id": "1",
          "title": "Students"
        }
      ],
      "role_assignment": "USER"
    },
    {
      "inviteLink": "EFGH5678",
      "expires": 1674052194,
      "group_assignments": [
        {
          "id": "2",
          "title": "TAs"
        }
      ],
      "role_assignment": "ADMIN"
    }
  ],
  "next": null
}
```

The request will fail if:

 - The project ID from the header is not the same as the project ID of the token.
 - The user is not an admin or PI of the project,


### `deleteInviteLink`

Request for deactivating a link. This deletes the link from the database table completely.

 
```kotlin
data class DeleteInviteLinkRequest(
    val token: String
)
```

```kotlin
typealias DeleteInviteLinkResponse = Unit
```

The request will fail if:

 - The project ID from the header is not the same as the project ID of the token.
 - The user is not an admin or PI of the project.


### `updateInviteLinkRoleAssignment`

Request for updating the role assignment of an invite link. This will update the `role_assignment` column in the `invite_links` table.

```kotlin
data class UpdateInviteLinkRoleAssignmentRequest(
    val token: String,
    val role: ProjectRole
)
```

```kotlin
typealias UpdateInviteLinkRoleAssignmentResponse = Unit
```

This request will fail if:


 - The project ID from the header is not the same as the project ID of the token.
 - The user is not an admin or PI of the project.
 - `role` is set to `ProjectRole.PI`.


### `updateInviteLinkGroupAssignment`

Request for updating the group assignment of the invite link. This will update the entries in the `invite_link_group_assignments` table. This involves both deleting from and inserting into the table.

```kotlin
data class UpdateInviteLinkGroupAssignmentRequest(
    val token: String,
    val groups: List<String>
)
```

```kotlin
typealias UpdateInviteLinkGroupAssignmentResponse = Unit
```

Should fail if:

 - The project ID from the header is not the same as the project ID of the token.
 - The user is not admin or PI of the project.

## Join Project UI and API

Invitees clicking the link will be able to join the project whether they have a user or not. In the last case however, the user will have to create a user before being able to *actually* join the project.

The workflow is slightly different, depending on whether the invitee is logged in or not. Most of this behaviour is however already implemented in the front-end. Considering an invitee clicking on an invite link `/app/projects/invite?id=ABCD1234`.

If the invitee is not logged in

 - the invitee is redirected to the normal log-in page of UCloud.
 - The user is then redirected back to the `/app/projects/invite?id=ABCD1234` page.

This behaviour is already implemented.

In case the invitee is already logged in as a user (or the user have just logged in by following the previous steps),

  - a request will be sent to the backend using the API described below,
  - the current project context of the user is changed, and
  - the user is redirected to an appropriate page (i.e. the *Dashboard* or *Drives* page).

### `acceptInviteLink`

End-point for joining a project through an invite link.

```kotlin
data class AcceptInviteLinkRequest(
    val token: String
)
```

```kotlin
typealias AcceptInviteLinkResponse = Unit
```

This will look up the invite token in `projects.invite_links` and find the ID of the project. then add the user to the list of project members by going through the same procedures as the existing `acceptInvite` functionality (except checking if an invitation exists).

The project role of the invitee will be set to `role_assignment`.

If any group assignments are defined (in the `invite_link_group_assignment` table) for the token, the invitee will be added to the project group if it exists, otherwise the user will not be added to any project groups.

Other behaviour and edge-cases include:

 - If the invitee is already a member of the project do nothing (repond `OK`),
 - if the link is expired throw an error.
 - if the link does not exist throw an error.
