### ISSUE TITLE
AllocationView is reducing amount incorrect and inconsitent

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3624]
In first row the last number is set to be kDKK while the first number is not, and the first number is somehow also multipled by 10.
The correct amount is shown when expanding the row. 

<img width="1157" alt="Screenshot 2022-08-25 at 14 01 39" src="https://user-images.githubusercontent.com/10943804/186659369-d5957f3b-fe7d-41db-bb6f-c55ee5172d8f.png">

**Comment by Tiggles** [comment]
For posterity, I believe that the issue stemmed from a rounding issue. The short hand `value | 0` was used, which is a way of doing a `Math.floor` like operation, but this approach yields an int32, so overflow will cause issues. Solved by using `Math.floor` prior to passing the args.

Regarding having kDKK on the right side and not on the left is intentional, if that is what is reference in the first line.

**Comment by claudiopica** [comment]
Hi @Tiggles I am not sure I understand the last line you wrote, but it does not make a lot of sense to use two different units.
Either we "attach" the 'k' to the number or we need to divide by 1000 both numbers.

**Comment by Tiggles** [comment]
Both are divided by 1000 when one is. The lhs in this case is the result of the `| 0` being used, as mentionend above.
