### ISSUE TITLE
[Accessibility] Enlargened cursor can block tooltips

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3712]
The text should say "No allocations [...]"
![IMG_3396](https://user-images.githubusercontent.com/7610257/194041349-3dcdaaba-e7f1-4ea2-8a1e-927c0748804b.jpg)

**Comment by Tiggles** [comment]
It doesn't seem like we can get this size of the cursor, and responds accordingly.

We can hide the cursor, but depending on the Tooltip trigger size, this is even worse than the blocked text.

The cross-hair cursor would probably solve this the best, but it's a weird one to be using for these sorts of things.

**Comment by xiroV** [comment]
A position that isn't calculated based on the cursor-position (like on Github) would solve it. Not sure if that introduces other problems.

![image](https://user-images.githubusercontent.com/911284/207015576-71af04e8-5dd4-4d31-8be7-b410e30ff2a9.png)

Alternatively showing the tooltip above (as in "north of") the cursor instead of below could also solve it, but that would require calculating the height of the tooltip-box I guess?

**Comment by Tiggles** [comment]
Should work, yes.

**Comment by DanThrane** [comment]
This has been made a lot better in the new UI. But if you set to the maximum size in macOS the cursor will still block out the tooltip.
