### ISSUE TITLE
first login problem

### ISSUE THREAD

**Issue by ottacom** [SDU-eScience/UCloud#4137]
Hello ,
I tried to deploy Ucloud on my computer several times, but I'm always getting an error 403/401 when I try to login into the web interface.
I'm wondering if there is a specific host name that I have to use/configure since by the instructions (from launcher) I should use https://ucloud.localhost.direct but of corse is not into my hostsfile.
Thanks a lot.

**Comment by DanThrane** [comment]
Hi @ottacom 

The hostname you mention is indeed the correct one. You shouldn't need any additional configuration on your own machine since https://ucloud.localhost.direct has a publicly available DNS entry which resolves to `127.0.0.1`.

Did you try with https://ucloud.localhost.direct yet? If you did and you are still getting a 403 then there might be some hints at the problem from the backend log. You should be able to retrieve these by running the following commands:

```
./launcher svc backend sh # Opens a shell to the backend
```

Followed by:

```
root@backend $ cat /tmp/service.log
```

I hope this helps, but let me know if you have any issues.

**Comment by ottacom** [comment]
Hi There ,
It turned our that the DNS where the VM is located is not allowing me to call that address , su I put the entry ucloud.localhost.direct into the host file It should be the same.
But I'm still getting bad gateway , I'm sorry to bothering you , but the logs seems fine.
Any idea? 
Thanks a lot for you help.
![Screenshot 2024-02-12 at 12 02 13](https://github.com/SDU-eScience/UCloud/assets/5305194/ebd6ef43-b23c-4f72-84c0-e2ebe71f38f6)


08:57:53.028 () I cloud.micro.RedisFeature - Connected to redis at redis. Config is loaded from redis/hostname.
08:57:53.453 () D cloud.micro.ServerFeature - Installing server...
08:57:55.219 () I cloud.accounting.services.wallets.AccountingProcessor - This service has become the master responsible for handling Accounting proccessor events!
08:57:55.222 () I cloud.accounting.services.wallets.AccountingProcessor - Attempting to load postgres data.
08:57:55.258 () I cloud.accounting.services.wallets.AccountingProcessor - Loading wallets
08:57:55.274 () I cloud.accounting.services.wallets.AccountingProcessor - Loading allocations
08:57:55.290 () I cloud.accounting.services.wallets.AccountingProcessor - Loading applications that has not been synced
08:57:55.296 () I cloud.accounting.services.wallets.AccountingProcessor - Deposits granted un-synchronized applications
08:57:55.296 () I cloud.accounting.services.wallets.AccountingProcessor - Loading Gifts and deposits un-synchronized claims
08:57:55.886 () I cloud.accounting.services.wallets.AccountingProcessor - Load of DB done.
08:57:56.388 () I cloud.accounting.services.wallets.AccountingProcessor - Synching
08:57:57.303 () I cloud.accounting.services.wallets.AccountingProcessor - Synching of DB is done!
08:57:58.183 () I cloud.support.Server - Service started!
08:57:58.208 () WARNING cloud.slack.services.AlertSlackService - No alerting notifier configured. This will not produce any output!
08:57:58.209 () WARNING cloud.slack.services.SupportSlackService - No support notifier configured. This will not produce any output!
08:57:58.239 () I cloud.micro.ServiceRegistry$rootServer - RPC server started!
============ UCloud is ready ============
08:57:58.754 () I cloud.calls.server.RpcServer - Incoming call [b449]: auth.refresh
08:57:58.775 () I cloud.service.ScriptManager - Starting script: ScriptMetadata(id=accounting-low-funds, title=Accounting: Low Funds, whenToStart=Daily(hour=0, minute=0))
08:57:58.832 () I cloud.service.ScriptManager - Script has finished executing, it took 55.855503ms
08:57:58.836 () I cloud.service.ScriptManager - Starting script: ScriptMetadata(id=project-invite-link-cleanup, title=Projects: Clean-up Invite Links, whenToStart=Daily(hour=0, minute=0))
08:57:58.845 () D cloud.accounting.services.projects.v2.ProjectService - Cleaned up 0 expired project invite links
08:57:58.846 () I cloud.service.ScriptManager - Script has finished executing, it took 10.476992ms
08:57:58.849 () I cloud.service.ScriptManager - Starting script: ScriptMetadata(id=token-scan, title=Authentication: Token Scan, whenToStart=Daily(hour=0, minute=0))
08:57:58.856 () D cloud.calls.server.RpcServer -    Responding [b449]: auth.refresh
08:57:58.870 () I cloud.service.ScriptManager - Script has finished executing, it took 21.690391ms
08:57:58.873 () I cloud.service.ScriptManager - Starting script: ScriptMetadata(id=shares-invite-link-cleanup, title=Shares: Clean-up Invite Links, whenToStart=Daily(hour=0, minute=0))
08:57:58.878 () D cloud.accounting.util.ResourceService - Cleaned up 0 expired shares invite links
08:57:58.879 () I cloud.service.ScriptManager - Script has finished executing, it took 5.934813ms
08:57:58.941 () I cloud.calls.server.RpcServer - Incoming call [ce36]: auth.users.createNewUser
08:57:59.058 () D cloud.auth.services.TokenService - Creating and registering token for Person(id='user', role=ADMIN, firstNames='user', lastName='test', email=user@example.com, serviceLicenseAgreement=0, organizationId=null, twoFactorAuthentication=false, connections=[])
08:57:59.067 () D cloud.auth.services.TokenService - RefreshTokenAndUser(associatedUser=user, token=c1396428-9f0b-45d5-a50a-ccbecf6338b6, csrf=OZMt+8yk9P0MRIEGUZ3qXl44To1r0aI86KGz0i2Tsbmco2+zXrwiLkoUTOdmIn+Ji+5wbP9vpbtXt2Zz/ggVUA==, refreshTokenExpiry=null, publicSessionReference=8a52c2ec-d321-497d-8ce3-de30b143a171, expiresAfter=600000, scopes=[all:write], extendedBy=null, extendedByChain=[], userAgent=Ktor client, ip=localhost, createdAt=1707728279050)
08:57:59.107 () D cloud.calls.server.RpcServer -    Responding [ce36]: auth.users.createNewUser
08:58:27.424 () I cloud.accounting.services.wallets.AccountingProcessor - Synching
08:58:27.482 () I cloud.accounting.services.wallets.AccountingProcessor - Synching of DB is done!
08:58:50.558 () I cloud.calls.server.RpcServer - Incoming call [675f]: auth.refresh
08:58:50.751 () D cloud.calls.server.RpcServer -    Responding [675f]: auth.refresh
08:58:51.462 () I cloud.calls.server.RpcServer - Incoming call [ddfc]: auth.refresh
08:58:51.470 () D cloud.calls.server.RpcServer -    Responding [ddfc]: auth.refresh
08:58:51.774 () I cloud.calls.server.RpcServer - Incoming call [6519]: hpc.apps.devImport
08:58:57.562 () I cloud.accounting.services.wallets.AccountingProcessor - Synching
08:58:58.069 () I cloud.accounting.services.wallets.AccountingProcessor - Synching of DB is done!
08:59:00.351 () D cloud.calls.server.RpcServer -    Responding [6519]: hpc.apps.devImport
08:59:28.149 () I cloud.accounting.services.wallets.AccountingProcessor - Synching

**Comment by DanThrane** [comment]
Unfortunately the DNS part of the setup isn't optional in a fully functional setup. Without it, several things will definitely break. Adding an entry in your hosts file and then accessing the gateway will get you some part of the way: 
https://github.com/SDU-eScience/UCloud/blob/abb29457a3eb512acc73479223e82cd6c3bf71ef/launcher-tool/src/main/kotlin/ComposeFile.kt#L1122

But in order to get a fully functional system, you will need the DNS setup. Interactive applications are an example of a feature which simply cannot work without it.

You might be able to make it work without the DNS if you accept such features don't work. In that case, you will need to update the appropriate configuration files:

- The frontend will need to point to the correct API https://github.com/SDU-eScience/UCloud/blob/abb29457a3eb512acc73479223e82cd6c3bf71ef/frontend-web/webclient/package.json#L7-L9
- Several backend configuration files might need to be updated
- Configuration of each provider need to have several properties updated

Running it through the `./launcher` script is by far the easiest approach. In case it helps, the `./launcher` is capable of starting a cluster running both locally and on a remote machine with SSH. You only need Java on the host machine if you wish to run it on another machine via SSH.

**Comment by ottacom** [comment]
Hi @DanThrane  Thanks , so I. moved the VM into a more open cloud and it's working!!! Yes the DNS can't be override.
Thanks a lot for your time and your exhaustive explanations!
I'm closing the case!
THANKS AGAIN!

**Comment by ottacom** [comment]
Hi @DanThrane  Thanks , so I. moved the VM into a more open cloud and it's working!!! Yes the DNS can't be override.
Thanks a lot for your time and your exhaustive explanations!
I'm closing the case!
THANKS AGAIN!
