### ISSUE TITLE
Archive of old projects

### ISSUE THREAD

**Issue by robertABsmith** [SDU-eScience/UCloud#4378]
Old projects are cluttering the project view for user profiles. Will it be possible to change the state of a project to archived in order to limit the number of projects shown in the project selection dropdown?

**Comment by Tiggles** [comment]
Hi,

We removed archival of projects as we don't think that version of it was that useful.

I know it's not what you are asking (essentially the opposite behavior), but if you favorite projects in the project-switcher, these will be pushed to the top of the list.

A recent change has been made so it's immediately is pushed to the top instead of first on re-opening the switcher.

We do intend on returning to archival of projects to do something more meaningful with them in the future.
